# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "faf01952054d2918d3493bc536d7cb36"
name = "order-sales-tag"
handle = "order-sales-tag"
application_url = "https://recipe-write-room-george.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "cartmade-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://recipe-write-room-george.trycloudflare.com/auth/callback",
  "https://recipe-write-room-george.trycloudflare.com/auth/shopify/callback",
  "https://recipe-write-room-george.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"
  include_fields = [ "id", "staff_member", "source_name" ]

[pos]
embedded = false
